[tool.poetry]
name = "tfc-test-writer-aider"
version = "0.1.0"
description = "A tool to assist with writing tests for TFC"
authors = ["Michael Lahr <michael.lahr@gmail.com>"]
readme = "README.md"
packages = [
    {include = "tfc_test_writer_aider", from = "src"},
    {include = "find_source_files", from = "src"},
    {include = "explain_code", from = "src"}
]

[tool.poetry.dependencies]
python = ">=3.11"
python-dotenv = "^1.0.0"

[tool.poetry.scripts]
tfc-test-writer = "src.tfc_test_writer_aider.cli:cli"
find-source-files = "src.find_source_files:main"
explain-code = "src.explain_code:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
