[tool.poetry]
name = "tfc-test-writer-aider"
version = "0.1.0"
description = ""
authors = ["Michael Lahr <michael.lahr@gmail.com>"]
package-mode = false
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
dotenv = "^0.9.9"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"