version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(threadName)s - %(levelname)s - %(name)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /tmp/tfc-code-pipeline.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  usual-suspects:
    level: INFO
  pipedrive:
    level: INFO
    handlers: [ console, file ]
    propagate: no
  pipedrive-sync:
    level: INFO
    handlers: [ console, file ]
    propagate: no

root:
  level: INFO
  handlers: [ console, file ]
  propagate: no
